### ISSUE TITLE
couldn't find "libretinafacencnn.so"

### ISSUE THREAD

**Issue by bear123445** [Ma0zii/ncnn-andriod-scrfd-app#1]
2023-12-25 09:10:43.861 9396-9396/com.example.retainfacencnn E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.retainfacencnn, PID: 9396
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.retainfacencnn--jEsEc-Mk2uuRnFRLvKwQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.retainfacencnn--jEsEc-Mk2uuRnFRLvKwQw==/lib/arm, /data/app/com.example.retainfacencnn--jEsEc-Mk2uuRnFRLvKwQw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libretinafacencnn.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.example.retainfacencnn.RetinaFace.<clinit>(RetinaFace.java:9)
        at com.example.retainfacencnn.MainActivity.<init>(MainActivity.java:32)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1175)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by Ma0zii** [comment]
Sorry, there may be some issues with this project. I'm not quite sure about the cause of this problem yet.
